---
# tasks file for wol

- name: Ensure the required packages are install on our wol client(s)
  package:
    name: "{{ wol_client_packages }}"
    state: present
  register: wol_client_packages_installed
  until: wol_client_packages_installed is succeeded
  retries: 3

- name: What is the clients target nic wol status right now?
  shell: >
    ethtool {{ {{ ansible_default_ipv4.interface }} }} | grep 'Wake-on' | tail -1 | awk '{print substr($0,length,1)}'
  register: wol_current_options

- name: Print the current wol status on our client
  debug:
    msg: "Current status is: {{ wol_current_options.stdout }}"

- name: Update client wol options if they are not equal to the current setting
  shell: >
    ethtool -s {{ wol_interface }} wol {{ wol_status }}
  when: "wol_options != wol_current_options.stdout"

